### ISSUE TITLE
请问使用 xps9360.sh 打开第三方应用权限的问题

### ISSUE THREAD

**Issue by jy007** [ymmshi/XPS-9360#10]
我使用了你的方法成功安装了黑苹果，请问不需要执行下面编译
**# 编译DSDT
bash XPS9360.sh --compile-dsdt**
的命令了吧？

是指执行这条命令吗？bash XPS9360.sh --enable-3rdparty

只需要打开第三方权限就好了吗？

**Comment by ymmshi** [comment]
不需要
是
