### ISSUE TITLE
我发现有遇到mic没有声音的情况插耳机也没有反应

### ISSUE THREAD

**Issue by 820Mockingjay** [ymmshi/XPS-9360#12]
我是直接装好了就使用了您的efi

**Comment by ymmshi** [comment]
kext utility 修复一下

**Comment by 820Mockingjay** [comment]
使用kext utility修复后还是没有声音，缓存也重建过了

**Comment by 820Mockingjay** [comment]
使用kext utility修复后mic还是没有声音，尝试多个人的efi都是无法使用mic

**Comment by ymmshi** [comment]
> 使用kext utility修复后mic还是没有声音，尝试多个人的efi都是无法使用mic

看一下声音的输入里面有没有选项
