### ISSUE TITLE
不同款CPU的需要重新配置哪些文件？

### ISSUE THREAD

**Issue by carking** [ymmshi/XPS-9360#14]
XPS 13 9350 
除了CPU为6560U，其他基本相同 
不太了解黑苹果，仅CPU型号不同要对EFI做哪些改动呢？ 谢谢

**Comment by ymmshi** [comment]
1. 显卡是HD540,需要重新设置
2. 生成CPUFriendDataProvider.kext

可以参考[hackintosh-stuff](https://github.com/hackintosh-stuff/XPS9350-macOS)或[远景](http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1842760&highlight=9350)的配置

**Comment by carking** [comment]
> 1. 显卡是HD540,需要重新设置
> 2. 生成CPUFriendDataProvider.kext
> 
> 可以参考[hackintosh-stuff](https://github.com/hackintosh-stuff/XPS9350-macOS)或[远景](http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1842760&highlight=9350)的配置

谢谢 显卡不同需要改动哪个KEXT？ config.plist需要更改哪些部分呢？
