### ISSUE TITLE
进不去系统

### ISSUE THREAD

**Issue by wax951223** [ymmshi/XPS-9360#9]
老哥用你的efi文件夹进不去系统啊……
用原先黑果那个可以进，但是核显没有驱动
除了SSD是东芝的XG5以外其他的配置都一样

**Comment by ymmshi** [comment]
安装前准备第四条做了没有

**Comment by wax951223** [comment]
grub里调参数那个也做了啊=。=直接用的d开头那老哥的文件

**Comment by ymmshi** [comment]
卡在哪里了贴张图看看
